services:
  outcomespillar.backend:
    image: outcomes-pillar-backend:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: outcomespillar-backend
    command: npx nest start --watch
    ports:
      - "3000:3000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './backend:/usr/src/app'
    networks:
      - govtool

  outcomespillar.ui:
    tty: true
    image: outcomes-pillar-ui:latest
    build:
      context: ./ui/
      dockerfile: Dockerfile.dev
    container_name: outcomespillar-ui
    entrypoint: ["sh", "-c", " npm run watch"]
    environment:
      - NODE_ENV=development
      - ROLLUP_WATCH=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './ui:/usr/src/app:cached'
    networks:
      - govtool

  govtool.frontend:
    tty: true
    image: node:20-alpine
    container_name: govtool-frontend
    working_dir: /app/govtool/frontend
    entrypoint: ["sh", "-c", " cd /app/ui && npm link &&  cd /app/govtool/frontend && npm link @intersect.mbo/govtool-outcomes-pillar-ui && npx vite --host --port 5173"]
    ports:
      - "5173:5173"
    environment:
      - VITE_IS_PROPOSAL_DISCUSSION_FORUM_ENABLED=true
      - VITE_IS_GOVERNANCE_OUTCOMES_PILLAR_ENABLED=true
      - VITE_APP_ENV=development
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
    - './govtool/frontend:/app/govtool/frontend'
    - './ui/:/app/ui'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - govtool

networks:
  govtool:
    driver: bridge
