FROM node:22-alpine AS base

RUN apk add --no-cache git bash

WORKDIR /app

RUN git clone https://github.com/IntersectMBO/govtool.git /app

WORKDIR /app/govtool/frontend

RUN yarn install

COPY ui /app/govtool/frontend/node_modules/@intersect.mbo/govtool-outcomes-pillar-ui

RUN yarn build

RUN  cp .env.example .env

EXPOSE 5173

ENTRYPOINT ["npx vite --host --port 5173"]