FROM node:20-alpine

RUN apk add --no-cache git bash

WORKDIR /app

RUN git clone https://github.com/IntersectMBO/govtool.git /app

COPY start-govtool.sh /usr/local/bin/start-govtool.sh

RUN chmod +x /usr/local/bin/start-govtool.sh

RUN git config --global --add safe.directory /app

RUN chown -R 777 .

EXPOSE 5173

ENTRYPOINT ["/usr/local/bin/start-govtool.sh"]