apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Chart.Name }}-ingress"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    release: "{{ $.Release.Name }}"
    service: "{{ $.Chart.Name }}-service"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirect-http-to-https@kubernetescrd,traefik-default-headers@kubernetescrd,traefik-strip-prefix@kubernetescrd"
spec:
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - {{ . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  rules:
    - host: 
        - {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Chart.Name }}-service"
                port:
                  number: 80
