apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Chart.Name }}-ingress-route"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ $.Chart.Name }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: wildcard-1694-tls
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/api`)
      kind: Rule
      priority: 1
      middlewares:
        - name: traefik-redirect-http-to-https@kubernetescrd
          namespace: traefik
        - name: traefik-default-headers@kubernetescrd
          namespace: traefik
        - name: traefik-redirect-to-www@kubernetescrd
          namespace: traefik
      services:
        - name: "{{ $.Chart.Name }}-service"
          namespace: {{ .Values.namespace }}
          port: 80
