namespace: govtool-outcomes-backend

image:
  repository: registry.lidonation.com/voltaire/outcomes.1694.io
  tag: 'latest'
  pullPolicy: IfNotPresent
  pullSecret: gitlab-registry-catalystexplorer
  replicaCount: 1

ingress:
  hosts: ''