namespace: outcomes-preview

image:
  repository: registry.lidonation.com/voltaire/govtool-outcomes-pillar/outcomes.1694.io
  tag: 'latest'
  pullPolicy: IfNotPresent
  pullSecret: '1694-registry-deploy-token'
  replicaCount: 1

ingress:
  hosts: ''