apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: cors-middleware
    namespace: {{ .Values.namespace }}
spec:
    headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
        accessControlAllowCredentials: false