name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      # Install dependencies
      - name: Install dependencies
        run: |
          cd ui
          yarn install --frozen-lockfile

      # Build the project
      - name: Build
        run: |
          cd ui
          yarn build

      # Audit signatures
      - name: Audit
        run: |
          cd ui
          yarn audit --groups dependencies

      # Release
      - name: Release
        working-directory: ui
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}